import ContributionForm from "@/components/contribution-form";
const paths=[
{n:"01",title:"Share a problem",time:"15–30 minutes",contribution:"Bring one genuine marine-processing, quality, supply-chain or market pain point from your work. It becomes an input to Opportunity Intelligence—not a commitment to join a project.",pathway:"A focused problem-framing conversation, a clearer innovation question and an invitation to continue only if the fit is useful."},
{n:"02",title:"Advise a sprint",time:"2–4 hours per month",contribution:"Review one defined TDS or development sprint: scale-up realism, critical parameters, market demand, regulation, quality or manufacturability.",pathway:"Documented expert recognition, visibility into the project outcome and first access to later co-development opportunities."},
{n:"03",title:"Co-develop a technology",time:"Sustained, milestone-based",contribution:"Own a bounded technical workstream and contribute domain expertise, evidence, review or execution over multiple milestones.",pathway:"Authorship or IP recognition where contribution qualifies, plus a possible venture pathway under a separate Vested Contributor agreement."},
{n:"04",title:"Provide access",time:"Defined per test or campaign",contribution:"Provide analytical capability, laboratory access, pilot-line time, equipment, samples, operating data or an industrial validation environment.",pathway:"A documented collaboration, appropriate recognition and a possible research, commercial or technology-access arrangement."},
{n:"05",title:"Mentor the build",time:"1–3 hours per month",contribution:"Guide grants, IP, governance, regulatory strategy, partnerships, finance, talent or venture execution around agreed decisions.",pathway:"A named advisory contribution and a route to a deeper formal role where sustained responsibility and mutual fit develop."}];
const sequence=["Express interest","20-minute introduction","Match to a problem or project","Agree scope and governance","Contribute to the work","Recognize and decide the next pathway"];
const faqs=[
["Do I need to leave my present job?","No. Most contribution paths are designed to work alongside an existing career. You remain responsible for your employer’s policies, conflict-of-interest rules, confidentiality obligations and any permission required."],
["Is this employment, volunteering or a partnership?","It is a governed contribution relationship. A contributor is not automatically an employee, legal partner, director or shareholder. Any different relationship requires its own written agreement."],
["Who owns the IP?","IP treatment is agreed before substantive work begins and depends on background IP, new inventions, facilities used, funding terms and the actual contribution. Nothing is assumed through a conversation alone."],
["Will I receive equity or authorship?","Neither is automatic. Authorship follows qualifying intellectual contribution and the applicable publication standard. Equity or venture participation is considered only for sustained, material contribution under a separate agreement."],
["How much time must I commit?","You can begin by sharing one problem in 15–30 minutes. Deeper paths are time-boxed or milestone-based, and the expected commitment is agreed before you start."],
["How is confidential information protected?","The first conversation should avoid employer-confidential or proprietary information. Where deeper exchange is needed, confidentiality, data access and permitted use are agreed in writing first."]];
export default function BuildTogether(){return <main className="build-page"><header className="founders-nav"><div className="shell nav-inner"><a href="/" className="brand">Lipi<span>Cure</span><small>MARINE BIOTECH TRANSLATION</small></a><a className="founders-back" href="/">← Return to the laboratory</a></div></header>
<section className="build-hero"><div className="shell build-hero-grid"><div><p className="eyebrow">The collaboration pathway</p><h1>Don’t just follow the idea.<br/><span>Help build what it becomes.</span></h1><p>LipiCure brings scientists, engineers, industry specialists and venture builders around defined marine-biotechnology translation problems. Contribution begins with real work, clear boundaries and a visible output.</p><div className="hero-actions"><a className="button-primary" href="#contribute">Choose your contribution <span>↗</span></a><a className="button-secondary" href="#open-project">See the live project <span>↓</span></a></div></div><div className="build-orb"><i/><small>COLLECTIVE INTELLIGENCE</small><strong>Science<br/>becomes<br/>technology</strong><em>CONTRIBUTION → EVIDENCE → VALUE</em></div></div></section>
<section className="build-principle"><div className="shell"><p className="eyebrow">Why this model</p><h2>India has powerful public research infrastructure. The missing layer is often coordinated translation.</h2><p>LipiCure does not aim to duplicate laboratories already built by universities, institutes and government. We identify a valuable problem, connect the right capability, structure the evidence pathway and carry the result toward IP, scale-up and use.</p><div className="principle-grid"><article><span>01</span><h3>Orchestrator, not owner of everything</h3></article><article><span>02</span><h3>Integrator, not duplicator</h3></article><article><span>03</span><h3>Contributor-built, clearly governed</h3></article></div></div></section>
<section className="open-project" id="open-project"><div className="shell project-open-grid"><div><p className="eyebrow">Open now · Omega-3 demonstration project</p><h2>A real project with multiple doors.</h2><p>The current pathway combines pelagic feedstock intelligence, low-temperature conditioning, lipid-quality preservation, chitosan-enabled purification, simulation and experimental validation.</p></div><div className="project-needs">{["Lipid chemistry and oxidation","Fish processing and feedstock","Chitosan and adsorption","DOE, simulation and digital twins","Analytical methods and contaminants","Pilot equipment and scale-up","Regulatory and IP strategy"].map(x=><span key={x}>{x}</span>)}</div></div></section>
<section className="contribution-paths"><div className="shell"><div className="section-head"><div><p className="eyebrow">Five ways to contribute</p><h2>Start at the level<br/>that fits your reality.</h2></div><p>Every door answers three questions plainly: what you do, the approximate time involved and what the pathway can give back. You can begin with one conversation and stop there without obligation.</p></div><div className="path-grid">{paths.map(p=><article key={p.n}><span>{p.n}</span><h3>{p.title}</h3><div className="time-chip">TIME · {p.time}</div><small>WHAT YOU DO</small><p>{p.contribution}</p><small>WHAT YOU GET</small><p>{p.pathway}</p></article>)}</div></div></section>
<section className="governed-build"><div className="shell governed-grid"><div><p className="eyebrow">How it works</p><h2>Clarity before commitment.</h2><p>Before meaningful work begins, the scope, expected output, confidentiality, data handling, recognition and applicable IP or authorship pathway are written down. LipiCure’s contributor governance framework is being formalized for this purpose.</p></div><ol>{sequence.map((x,i)=><li key={x}><span>{String(i+1).padStart(2,"0")}</span>{x}</li>)}</ol></div></section>
<section className="governance-faq"><div className="shell"><div className="section-head"><div><p className="eyebrow">Questions serious contributors ask</p><h2>Clear answers.<br/>No vague promises.</h2></div><p>Contributors are recognized participants in a governed exchange—not automatically employees, partners or shareholders.</p></div><div className="faq-grid">{faqs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></div></section>
<section className="intake-section" id="contribute"><div className="shell intake-grid"><div><p className="eyebrow">Structured contributor intake</p><h2>Bring one problem, capability or missing piece.</h2><p>Choose the contribution door that fits you and tell us what you can realistically offer. Jonobbas Baskaran, Strategic Founder, will review the submission and aim to respond within three working days.</p><div className="momentum-note"><i/><p>Industry professionals and academic scientists are already adding practical insight and scientific depth across LipiCure’s developing research and venture pathways.</p></div></div><ContributionForm/></div></section>
<footer className="build-invitation"><div className="shell"><p className="eyebrow">Democratizing marine-biotechnology translation</p><h2>Great technologies can begin with one well-framed problem.</h2><p>If the form is not convenient, connect directly on LinkedIn and mention the contribution tier that interests you.</p><a className="linkedin-build" href="https://www.linkedin.com/company/lipicure-deeptech/" target="_blank" rel="noreferrer">Visit LipiCure on LinkedIn ↗</a></div></footer></main>}
